/**
 * ORDROTATION — WORD LIBRARY
 * ─────────────────────────────────────────────────────────────────
 * Edit this file to add, remove, or change words.
 * The app (ordrotation.html) loads this automatically.
 *
 * FORMAT PER DECK
 * ───────────────
 * WORDS.verbs   → [infinitive, present, past, supine, english]
 * WORDS.nouns   → [swedish, gender, definite-sg, indefinite-pl, definite-pl, english]
 * WORDS.adj     → [base/en-form, neuter/ett-form, plural+definite, comparative, superlative, english]
 *                 Use "–" for any form that doesn't exist.
 * WORDS.adv     → [swedish, english]
 * WORDS.conj    → [category, swedish, english, example-sentence]
 * WORDS.phrases → [swedish, english, example-or-note]
 *
 * TIP: To add a word, just copy an existing row in the right section
 * and change the values. Keep the square brackets and commas intact.
 */

const WORDS = {

  verbs: [
    ["göra",      "gör",        "gjorde",       "gjort",       "to do / make"],
    ["skriva",    "skriver",    "skrev",         "skrivit",     "to write"],
    ["skada",     "skadar",     "skadade",       "skadat",      "to damage / hurt"],
    ["se",        "ser",        "såg",           "sett",        "to see"],
    ["le",        "ler",        "log",           "lett",        "to smile"],
    ["köpa",      "köper",      "köpte",         "köpt",        "to buy"],
    ["flyga",     "flyger",     "flög",          "flugit",      "to fly"],
    ["åka",       "åker",       "åkte",          "åkt",         "to go / travel (by vehicle)"],
    ["lägga",     "lägger",     "la / lade",     "lagt",        "to lay / put"],
    ["ta",        "tar",        "tog",           "tagit",       "to take"],
    ["väva",      "väver",      "vävde",         "vävt",        "to weave"],
    ["hålla",     "håller",     "höll",          "hållit",      "to hold"],
    ["leda",      "leder",      "ledde",         "lett",        "to lead"],
    ["lära",      "lär",        "lärde",         "lärt",        "to teach / learn"],
    ["undervisa", "undervisar", "undervisade",   "undervisat",  "to teach"],
    ["plocka",    "plockar",    "plockade",      "plockat",     "to pick (up)"],
    ["flytta",    "flyttar",    "flyttade",      "flyttat",     "to move"],
    ["klaga",     "klagar",     "klagade",       "klagat",      "to complain"],
    ["skälla",    "skäller",    "skällde",       "skällt",      "to bark"],
    ["tänka",     "tänker",     "tänkte",        "tänkt",       "to think"],
    ["fundera",   "funderar",   "funderade",     "funderat",    "to ponder"],
    ["förändra",  "förändrar",  "förändrade",    "förändrat",   "to change (modify)"],
    ["byta",      "byter",      "bytte",         "bytt",        "to change / swap"],
    ["hyra",      "hyr",        "hyrde",         "hyrt",        "to rent"],
    ["planera",   "planerar",   "planerade",     "planerat",    "to plan"],
    ["minnas",    "minns",      "mindes",        "mints",       "to remember"],
    ["öva",       "övar",       "övade",         "övat",        "to practice"],
    ["koka",      "kokar",      "kokade",        "kokat",       "to boil"],
    ["hända",     "händer",     "hände",         "hänt",        "to happen"],
    ["söka",      "söker",      "sökte",         "sökt",        "to search"],
    ["föredra",   "föredrar",   "föredrog",      "föredragit",  "to prefer"],
    ["införa",    "inför",      "införde",       "infört",      "to introduce / implement"],
    ["bero",      "beror",      "berodde",       "berott",      "to depend (på = on)"],
    ["vänta",     "väntar",     "väntade",       "väntat",      "to wait (på = for)"],
    ["vakna",     "vaknar",     "vaknade",       "vaknat",      "to wake up"],
    ["stiga",     "stiger",     "steg",          "stigit",      "to rise / get up (upp = up)"],
    ["cykla",     "cyklar",     "cyklade",       "cyklat",      "to cycle"],
    ["tycka",     "tycker",     "tyckte",        "tyckt",       "to think / feel (om = like)"],
    ["arbeta",    "arbetar",    "arbetade",      "arbetat",      "to work"],
    ["laga",      "lagar",      "lagade",        "lagat",       "to cook / fix"],
    ["behöva",    "behöver",    "behövde",       "behövt",      "to need"],
    ["få",        "får",        "fick",          "fått",        "to get / be allowed to"],
    ["titta",     "tittar",     "tittade",       "tittat",      "to look (på = at) / watch"],
    ["köra",      "kör",        "körde",         "kört",        "to drive"],
    ["försöka",   "försöker",   "försökte",      "försökt",     "to try"],
    ["träna",     "tränar",     "tränade",       "tränat",      "to exercise / train"],
    ["regna",     "regnar",     "regnade",       "regnat",      "to rain"],
    ["lyssna",    "lyssnar",    "lyssnade",      "lyssnat",     "to listen"],
    ["bruka",     "brukar",     "brukade",       "brukat",      "to usually do"],
    ["promenera", "promenerar", "promenerade",   "promenerat",  "to walk / stroll"],
    ["prata",     "pratar",     "pratade",       "pratat",      "to talk"],
    ["handla",    "handlar",    "handlade",      "handlat",     "to shop / be about"],
    ["segla",     "seglar",     "seglade",       "seglat",      "to sail"],
    ["fika",      "fikar",      "fikade",        "fikat",       "to have coffee / socialise"],
    ["hosta",     "hostar",     "hostade",       "hostat",      "to cough"],
    ["träffa",    "träffar",    "träffade",      "träffat",     "to meet"],
    ["resa",      "reser",      "reste",         "rest",        "to travel"],
    ["hjälpa",    "hjälper",    "hjälpte",       "hjälpt",      "to help"],
    ["bo",        "bor",        "bodde",         "bott",        "to live / reside"],
    ["äta",       "äter",       "åt",            "ätit",        "to eat"],
  ],

  nouns: [
    ["golv",           "ett", "golvet",           "golv",              "golven",              "floor"],
    ["kemi",           "en",  "kemin",            "–",                 "–",                   "chemistry"],
    ["kärlek",         "en",  "kärleken",         "–",                 "–",                   "love"],
    ["skiva",          "en",  "skivan",           "skivor",            "skivorna",            "record / slice / disc"],
    ["sko",            "en",  "skon",             "skor",              "skorna",              "shoe"],
    ["skada",          "en",  "skadan",           "skador",            "skadorna",            "injury / damage"],
    ["hål",            "ett", "hålet",            "hål",               "hålen",               "hole"],
    ["håll",           "ett", "hållet",           "håll",              "hållen",              "direction / way"],
    ["lycka",          "en",  "lyckan",           "–",                 "–",                   "happiness"],
    ["olycka",         "en",  "olyckan",          "olyckor",           "olyckorna",           "accident / misfortune"],
    ["borr",           "en",  "borren",           "borrar",            "borrarna",            "drill"],
    ["matta",          "en",  "mattan",           "mattor",            "mattorna",            "rug / mat"],
    ["glas",           "ett", "glaset",           "glas",              "glasen",              "glass (material/cup)"],
    ["glass",          "en",  "glassen",          "glassar",           "glassarna",           "ice cream"],
    ["regel",          "en",  "regeln",           "regler",            "reglerna",            "rule / regulation"],
    ["lag",            "en",  "lagen",            "lagar",             "lagarna",             "law"],
    ["lag",            "ett", "laget",            "lag",               "lagen",               "team"],
    ["uttal",          "ett", "uttalet",          "–",                 "–",                   "pronunciation"],
    ["tal",            "ett", "talet",            "tal",               "talen",               "speech / number"],
    ["hotell",         "ett", "hotellet",         "hotell",            "hotellen",            "hotel"],
    ["kattungekull",   "en",  "kattungekullen",   "kattungekullar",    "kattungekullarna",    "litter of kittens"],
    ["bild",           "en",  "bilden",           "bilder",            "bilderna",            "picture"],
    ["kattunge",       "en",  "kattungen",        "kattungar",         "kattungarna",         "kitten"],
    ["katt",           "en",  "katten",           "katter",            "katterna",            "cat"],
    ["förälder",       "en",  "föräldern",        "föräldrar",         "föräldrarna",         "parent"],
    ["bror",           "en",  "brodern",          "bröder",            "bröderna",            "brother"],
    ["granne",         "en",  "grannen",          "grannar",           "grannarna",           "neighbour"],
    ["lägenhet",       "en",  "lägenheten",       "lägenheter",        "lägenheterna",        "apartment"],
    ["problem",        "ett", "problemet",        "problem",           "problemen",           "problem"],
    ["orsak",          "en",  "orsaken",          "orsaker",           "orsakerna",           "cause / reason"],
    ["del",            "en",  "delen",            "delar",             "delarna",             "part"],
    ["vikt",           "en",  "vikten",           "vikter",            "vikterna",            "weight"],
    ["kaffe",          "ett", "kaffet",           "–",                 "–",                   "coffee"],
    ["kafé",           "ett", "kaféet",           "kaféer",            "kaféerna",            "cafe"],
    ["lektion",        "en",  "lektionen",        "lektioner",         "lektionerna",         "lesson"],
    ["relation",       "en",  "relationen",       "relationer",        "relationerna",        "relationship"],
    ["körkort",        "ett", "körkortet",        "körkort",           "körkorten",           "driver's licence"],
    ["uteplats",       "en",  "uteplatsen",       "uteplatser",        "uteplatserna",        "patio"],
    ["trädgård",       "en",  "trädgården",       "trädgårdar",        "trädgårdarna",        "garden"],
    ["buske",          "en",  "busken",           "buskar",            "buskarna",            "bush"],
    ["ränta",          "en",  "räntan",           "räntor",            "räntorna",            "interest (rate/fee)"],
    ["mitt",           "en",  "mitten",           "–",                 "–",                   "the middle"],
    ["hemläxa",        "en",  "hemläxan",         "hemläxor",          "hemläxorna",          "homework assignment"],
    ["regering",       "en",  "regeringen",       "regeringar",        "regeringarna",        "government"],
    ["bidrag",         "ett", "bidraget",         "bidrag",            "bidragen",            "grant / assistance"],
    ["studiegrupp",    "en",  "studiegruppen",    "studiegrupper",     "studiegrupperna",     "study group"],
    ["verkstad",       "en",  "verkstaden",       "verkstäder",        "verkstäderna",        "workshop"],
    ["bil",            "en",  "bilen",            "bilar",             "bilarna",             "car"],
    ["hus",            "ett", "huset",            "hus",               "husen",               "house"],
    ["mormor",         "en",  "mormor",           "mormödrar",         "mormödrarna",         "grandmother (mother's side)"],
    ["sambo",          "en",  "sambon",           "sambor",            "samborna",            "live-in partner"],
    ["chef",           "en",  "chefen",           "chefer",            "cheferna",            "boss"],
    ["barn",           "ett", "barnet",           "barn",              "barnen",              "child"],
    ["advokatfirma",   "en",  "advokatfirman",    "advokatfirmor",     "advokatfirmorna",     "law firm"],
    ["engelsman",      "en",  "engelsmannen",     "engelsmän",         "engelsmännen",        "Englishman"],
    ["kompis",         "en",  "kompisen",         "kompisar",          "kompisarna",          "friend"],
    ["arbetskompis",   "en",  "arbetskompisen",   "arbetskompisar",    "arbetskompisarna",    "work colleague"],
    ["resa",           "en",  "resan",            "resor",             "resorna",             "trip / journey"],
    ["middag",         "en",  "middagen",         "middagar",          "middagarna",          "dinner"],
    ["flygplats",      "en",  "flygplatsen",      "flygplatser",       "flygplatserna",       "airport"],
    ["tåg",            "ett", "tåget",            "tåg",               "tågen",               "train"],
    ["kläder",         "–",   "kläderna",         "kläder",            "kläderna",            "clothes (plural only)"],
    ["sak",            "en",  "saken",            "saker",             "sakerna",             "thing"],
    ["grej",           "en",  "grejen",           "grejer",            "grejerna",            "thing / stuff (informal)"],
    ["mobil",          "en",  "mobilen",          "mobiler",           "mobilerna",           "mobile phone"],
    ["mening",         "en",  "meningen",         "meningar",          "meningarna",          "sentence / opinion"],
    ["stad",           "en",  "staden",           "städer",            "städerna",            "city / town"],
    ["visning",        "en",  "visningen",        "visningar",         "visningarna",         "viewing / showing"],
    ["helg",           "en",  "helgen",           "helger",            "helgerna",            "weekend"],
    ["skridsko",       "en",  "skridskon",        "skridskor",         "skridskorna",         "ice skate"],
    ["kusin",          "en",  "kusinen",          "kusiner",           "kusinerna",           "cousin"],
    ["hosta",          "en",  "hostan",           "–",                 "–",                   "a cough"],
    ["påve",           "en",  "påven",            "påvar",             "påvarna",             "pope"],
    ["pojke",          "en",  "pojken",           "pojkar",            "pojkarna",            "boy"],
    ["tröja",          "en",  "tröjan",           "tröjor",            "tröjorna",            "sweater"],
  ],

  adj: [
    ["mysig",       "mysigt",       "mysiga",       "mysigare",       "mysigast",       "cozy"],
    ["fin",         "fint",         "fina",         "finare",         "finast",         "nice / fine"],
    ["glad",        "glatt",        "glada",        "gladare",        "gladast",        "happy"],
    ["dyr",         "dyrt",         "dyra",         "dyrare",         "dyrast",         "expensive"],
    ["liten",       "litet",        "små",          "mindre",         "minst",          "small (irregular)"],
    ["trevlig",     "trevligt",     "trevliga",     "trevligare",     "trevligast",     "pleasant"],
    ["romantisk",   "romantiskt",   "romantiska",   "romantiskare",   "romantiskast",   "romantic"],
    ["läskig",      "läskigt",      "läskiga",      "läskigare",      "läskigast",      "scary"],
    ["japansk",     "japanskt",     "japanska",     "–",              "–",              "Japanese"],
    ["rolig",       "roligt",       "roliga",       "roligare",       "roligast",       "fun / funny"],
    ["gammal",      "gammalt",      "gamla",        "äldre",          "äldst",          "old (irregular)"],
    ["söt",         "sött",         "söta",         "sötare",         "sötast",         "cute / sweet"],
    ["svart",       "svart",        "svarta",       "svartare",       "svartast",       "black"],
    ["stor",        "stort",        "stora",        "större",         "störst",         "big (irregular)"],
    ["kall",        "kallt",        "kalla",        "kallare",        "kallast",        "cold"],
    ["förkyld",     "förkylt",      "förkylda",     "–",              "–",              "having a cold"],
    ["ny",          "nytt",         "nya",          "nyare",          "nyast",          "new"],
    ["gul",         "gult",         "gula",         "gulare",         "gulast",         "yellow"],
    ["hög",         "högt",         "höga",         "högre",          "högst",          "high / tall (irregular)"],
    ["nöjd",        "nöjt",         "nöjda",        "nöjdare",        "nöjdast",        "satisfied"],
    ["ledig",       "ledigt",       "lediga",       "ledigare",       "ledigast",       "free / available"],
    ["viktig",      "viktigt",      "viktiga",      "viktigare",      "viktigast",      "important"],
    ["ensam",       "ensamt",       "ensamma",      "ensammare",      "ensammast",      "alone"],
    ["nyfiken",     "nyfiket",      "nyfikna",      "nyfiknare",      "nyfiknast",      "curious"],
    ["spänd",       "spänt",        "spända",       "spändare",       "spändast",       "excited / tense"],
    ["gift",        "gift",         "gifta",        "–",              "–",              "married"],
    ["full",        "fullt",        "fulla",        "fullare",        "fullast",        "full / drunk"],
    ["ful",         "fult",         "fula",         "fulare",         "fulast",         "ugly"],
    ["olika",       "olika",        "olika",        "–",              "–",              "different (invariable)"],
    ["förra",       "förra",        "förra",        "–",              "–",              "last / previous (invariable)"],
    ["nuvarande",   "nuvarande",    "nuvarande",    "–",              "–",              "current (invariable)"],
    ["trött",       "trött",        "trötta",       "tröttare",       "tröttast",       "tired"],
    ["ledsen",      "ledset",       "ledsna",       "ledsnare",       "ledsnast",       "sad"],
    ["vänlig",      "vänligt",      "vänliga",      "vänligare",      "vänligast",      "friendly"],
    ["ekonomisk",   "ekonomiskt",   "ekonomiska",   "–",              "–",              "economic"],
    ["arbetslös",   "arbetslöst",   "arbetslösa",   "–",              "–",              "unemployed"],
    ["intressant",  "intressant",   "intressanta",  "intressantare",  "intressantast",  "interesting"],
    ["tidig",       "tidigt",       "tidiga",       "tidigare",       "tidigast",       "early"],
    ["vanlig",      "vanligt",      "vanliga",      "vanligare",      "vanligast",      "usual"],
  ],

  adv: [
    ["sällan",        "rarely / seldom"],
    ["nästa",         "next"],
    ["nästan",        "almost"],
    ["ganska",        "quite"],
    ["än",            "than"],
    ["dit",           "to there (movement towards)"],
    ["där",           "there (static location)"],
    ["igen",          "again"],
    ["ut",            "out"],
    ["fortfarande",   "still"],
    ["imorse",        "this morning (past)"],
    ["imorgon bitti", "tomorrow morning"],
    ["hem",           "home(wards)"],
    ["tillbaka",      "back"],
    ["först",         "first"],
    ["då",            "then / at that point / since"],
    ["sedan",         "then / after / since"],
    ["åt",            "towards / for"],
    ["hos",           "at (someone's home/place)"],
    ["flera",         "several"],
    ["fler",          "more (count)"],
    ["flesta",        "most"],
    ["nåt / något",   "something"],
    ["en gång till",  "one more time"],
    ["vem som helst", "anyone / whoever"],
    ["per gång",      "per time / each time"],
  ],

  conj: [
    ["Coordinating",   "och",                   "and",                  ""],
    ["Coordinating",   "men",                   "but",                  ""],
    ["Coordinating",   "eller",                 "or",                   ""],
    ["Coordinating",   "för",                   "because / for",        ""],
    ["Coordinating",   "så",                    "so",                   ""],
    ["Coordinating",   "utan",                  "but rather / without", ""],
    ["Reason",         "eftersom",              "since / because",      "Jag stannar hemma eftersom jag är sjuk."],
    ["Reason",         "därför att",            "because",              "Jag äter därför att jag är hungrig."],
    ["Reason",         "då",                    "since / as",           "Då det regnade tog jag paraply."],
    ["Time",           "när",                   "when",                 "När det regnar tar jag paraply."],
    ["Time",           "medan",                 "while",                "Nils tar en tupplur medan hans sambo duschar."],
    ["Time",           "innan",                 "before",               "Jag måste diska innan vi går ut."],
    ["Time",           "då",                    "when (that time)",     "Hösten är en tid då det regnar mycket."],
    ["Time",           "inte förrän",           "not until",            ""],
    ["Condition",      "om",                    "if",                   "Jag äter om jag är hungrig."],
    ["Condition",      "ifall",                 "in case",              "Ifall det regnar tar jag paraply."],
    ["Result",         "så att",                "so that",              "Jag tog paraply så att jag inte skulle bli våt."],
    ["Purpose",        "för att",               "in order to",          "Jag tog paraply för att inte bli våt."],
    ["Purpose",        "genom att",             "by (doing)",           "Du kan lära dig mycket genom att repetera ofta."],
    ["Manner",         "utan att",              "without (doing)",      "Jag kan inte förstå filmer utan att läsa texten."],
    ["Contrast",       "trots att",             "despite",              "Christina ska bada trots att det är kallt."],
    ["Contrast",       "även om",               "even though",          "Jag tränar varje dag även om det regnar."],
    ["Contrast",       "fastän",                "although",             "Jag åt fastän jag var mätt."],
    ["General",        "att",                   "that",                 "Jag sa att jag var hungrig."],
    ["Interrogative",  "om",                    "whether",              "Hon frågade om jag var hungrig."],
    ["Comparative",    "som",                   "as",                   "Han sjöng som Michael Jackson."],
    ["Comparative",    "såsom",                 "such as",              ""],
    ["Comparative",    "ju...desto",            "the more...the more",  "Ju mer jag äter desto mättare blir jag."],
    ["Relative",       "som",                   "that / which / who",   "Sverige är ett land som har mycket regn."],
    ["Relative",       "vilken / vilket / vilka","which",               ""],
    ["Relative",       "där",                   "where",                "Sverige är ett land där det regnar mycket."],
    ["Relative",       "då",                    "when (relative)",      "Hösten är en tid då det regnar mycket."],
  ],

  phrases: [
    ["se ut",                           "to look / appear (+ adjective)",          "Hon såg trevlig ut."],
    ["tycka om",                        "to like",                                  "Hunden tycker om att vara med dig."],
    ["hålla med",                       "to agree",                                 "Jag håller med."],
    ["komma ihåg",                      "to remember",                              "Jag kommer inte ihåg."],
    ["göra åt",                         "to do about (a problem)",                  "Vad kan man göra åt detta?"],
    ["tänka på",                        "to think about",                           "Jag tänker på min vän."],
    ["titta på",                        "to watch / look at",                       "Jag tycker om att titta på TV."],
    ["lägga sig",                       "to go to bed",                             "Jag gick och la mig."],
    ["plocka upp",                      "to pick up",                               "Vi plockade upp två kattungar."],
    ["vänta på",                        "to wait for",                              "Jag väntar på bussen."],
    ["bero på",                         "to depend on",                             "Det beror på vädret."],
    ["nöjd med",                        "satisfied with",                           "Han är nöjd med sitt nya jobb."],
    ["mitt i stan",                     "in the middle of town",                    ""],
    ["i fredags / i tisdags / i lördags","last Friday / Tuesday / Saturday",        "i + weekday + s = last (that weekday)"],
    ["jag har inga frågor",             "I have no questions",                      "ingen/inget/inga negates the noun directly"],
    ["jag är spänd",                    "I'm excited",                              ""],
    ["jag är förkyld",                  "I have a cold",                            ""],
  ],

};
